### ISSUE TITLE
docs: `timeout` not documented

### ISSUE THREAD

**Issue by eins78** [cider-ci/cider-ci#13]
Right now this is the only information about `timeout` I could find: https://github.com/cider-ci/cider-ci_demo-project-bash/search?utf8=✓&q=timeout

**Comment by DrTom** [comment]
This is correct. `timeout` is not documented yet. 
There will also be a change/extension towards human readable durations like `5 Minutes` probably in 3.8. 
I will hold on documenting until that is done. 

For the time being: the int value is interpreted as Seconds for scripts.

**Comment by DrTom** [comment]
Done, see http://docs.cider-ci.info/search.html?term=timeout
