### ISSUE TITLE
Failed to stop 9.4.service

### ISSUE THREAD

**Issue by pape-io** [cider-ci/cider-ci#17]
Cider-CI_3.8.0-12.beta
```
< TASK: postgresql | restart postgresql >
 --------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


failed: [server] => {"failed": true}
msg: Failed to stop 9.4.service: Unit 9.4.service not loaded.
Failed to start 9.4.service: Unit 9.4.service failed to load: No such file or directory.
```

**Comment by DrTom** [comment]
Strange. Is this a clean install or an upgrade?

**Comment by pape-io** [comment]
upgrade, I skipped that particular task for now

**Comment by pape-io** [comment]
I will try this particular task later again in order to debug

**Comment by DrTom** [comment]
Even stranger, I upgraded this version too without problems. 
But I didn't try with wheezy, I'll check if I can reproduce it there.

**Comment by DrTom** [comment]
I can reproduce this with Jessie. Seems to be a problem when a reload comes too quickly with that version of  systemd. I will look for a workaround.

**Comment by DrTom** [comment]
fix in https://github.com/cider-ci/cider-ci/releases/tag/Cider-CI_3.8.0-16.beta
resp https://github.com/DrTom/ansible-role-postgresql/commit/7182e5e940b795f09869bc0dc96e2af3b4893858
