### ISSUE TITLE
Improve long loading times "My Workspace" filters

### ISSUE THREAD

**Issue by DrTom** [cider-ci/cider-ci#27]
Selecting certain filters which include projects with many branches and a long history can
result in (very) long query times (up to several minutes) and resulting loading times for the "My Worspace" page. 

What we can do: 

1. Time out long queries and reset the filters automatically. 
2. Consider to remove the depth parameter and only offer "Heads" or "Any".

**Comment by pape-io** [comment]
Maybe it's worth considering a timeout configuration for the http-reverse-proxy that drains after some seconds

**Comment by DrTom** [comment]
Further investigation revealed that the machine which produced the problem turns out to have very bad IO performance.

**Comment by DrTom** [comment]
Fixed in 3.13
