### ISSUE TITLE
trial state: distinction between 'ci error' and 'test error'

### ISSUE THREAD

**Issue by eins78** [cider-ci/cider-ci#3]
Some trials error before any actual tests are run ([ex.](http://ci2.zhdk.ch/cider-ci/ui/workspace/trials/78a8b7c7-2aa2-49ea-81c3-3222c23dd993)).

It might be interesting to consider this a different state than just "error", since we don't know if the test would have succeeded…

For projects that have a more strict "retrial" policy (right none there are none…), it would mean that a problem with a single executor can make the whole execution fail till someone clicks the 'retry' button.

I'm not quite sure, but one could go even so far as to *always* re-try such "early-errored" trials (even if just to not make the config even more complicated).

**Comment by DrTom** [comment]
I'll think about it. V3 already has 2 more states: skipped and aborted. 

Btw., the example seem to have failed because of a timeout.

**Comment by DrTom** [comment]
Everything seems to be now in order to do this. We will use the state `aborted`.

**Comment by eins78** [comment]
I like `aborted` because it communicates it being a "non-state", it did not even start.
But what about "aborting jobs"? Not sure if it is good or bad to use the same term in both places. 
Let's try it out ;)

**Comment by DrTom** [comment]
This is partially implemented in the meanwhile: when an executor disappears the trial is marked aborted. There have been no issues with this and it seems it could be extended to similar cases.

**Comment by DrTom** [comment]
There are some cases where 'aborted', and 'failed' are not sufficient. We need an additional state `error` to identify bad executors and disable or suspend them.

**Comment by DrTom** [comment]
As if 4.0.0-BETA+0 there is a `defective` state for this.

**Comment by DrTom** [comment]
Closing this since the requested feature is available since 4.0 is official.
