### ISSUE TITLE
Tree view doesn't show all expected commits 

### ISSUE THREAD

**Issue by DrTom** [cider-ci/cider-ci#30]
> Cider bug? Ich sehe hier die ​_Jobs_​ vom datalayer aber nicht den ​_Commit_​: https://ci.zhdk.ch/cider-ci/ui/workspace/trees/eb5060e4f63d8c0692b03c99a9196121cda166af

@eins78 FYI

**Comment by eins78** [comment]
> Der letzte Commit in der Liste ​_ist_​ der aus dem Datalayer… der bug ist also “nur” das er nicht den neuesten findet. Hier stimmts: https://ci.zhdk.ch/cider-ci/ui/workspace/jobs/bc0abcae-96d1-4f08-92d2-10373b434686

**Comment by DrTom** [comment]
Closing this since I can't reproduce it.
