### ISSUE TITLE
Bug: job passes when no tasks are created

### ISSUE THREAD

**Issue by DrTom** [cider-ci/cider-ci#32]
e.g. https://ci.zhdk.ch/cider-ci/ui/workspace/jobs/c234465e-d66e-45ef-a5ce-77b4e398a4ad

commit: https://github.com/Madek/madek-webapp/commit/506eb384215035742452100b14df4d298be90863

**Comment by eins78** [comment]
First time it happened: https://ci.zhdk.ch/cider-ci/ui/workspace/jobs/b48c29e2-3f07-4d5d-9b7f-a7f47a36a2c2

**Comment by DrTom** [comment]
After thinking about it: this is the consistent behavior. As of 4.0.0-BETA.0 there will be a warning attached to the job if this happens.
