### ISSUE TITLE
v4: Repository configuration in UI

### ISSUE THREAD

**Issue by pape-io** [cider-ci/cider-ci#35]
BTW: What's with `Branch trigger include-match` & `Branch trigger exclude-match`. They recently appeared in the UI.

I thought the idea is that you configure cider though the cider.yml, checked into the app repository to its full extent?!?

**Comment by DrTom** [comment]
You can edit all fields via the UI if you like to do so.

The two new fields are additional to the project configuration. The practical use case is to prevent auto triggers for old v3 configurations in new v4 instances while migrating a project. You can't just do that with the project configuration. It doesn't know anything about the executor it is being run.

**Comment by DrTom** [comment]
See above.
