### ISSUE TITLE
Ping Github when Job was queued not when it actually got started

### ISSUE THREAD

**Issue by pape-io** [cider-ci/cider-ci#37]
![screen shot 2016-08-08 at 14 49 10](https://cloud.githubusercontent.com/assets/851393/17480270/5797a95a-5d77-11e6-839b-8fe20983e71c.png)

![screen shot 2016-08-08 at 14 49 04](https://cloud.githubusercontent.com/assets/851393/17480272/5a364afe-5d77-11e6-8b6e-a03d9f665ea5.png)

When Jobs are queued, Github doesn't show any information that the job has been arrived on Cider.

Would it be possible to ping github when the job got queued, rather then when it got started?

**Comment by DrTom** [comment]
I guess that would be possible.

**Comment by DrTom** [comment]
Had a look at this. The code should send "pending" and I can confirm that it does on `ci.zhdk.ch` for version `4.1.0`. Can you please recheck the behavior. 

GitHub seems to have removed some JavaScripted stuff on their pages. I am not sure if this was ever reloaded but you should manually reload the GH page.

**Comment by pape-io** [comment]
Can confirm, that works in v4
