### ISSUE TITLE
BUG: Working directories do not get removed properly, try cycle, log bloating

### ISSUE THREAD

**Issue by pape-io** [cider-ci/cider-ci#39]
For some reason Cider is not able to clear/delete working directories that contain symlinks.

```
ls -l /tmp/ci_working-dir/932300b9-c018-4a20-bcd2-7136b24f557d/public/
total 0
lrwxrwxrwx 1 ci-exec-user root 41 Aug 10 08:45 apple-touch-icon.png -> ../app/assets/images/local_logo_small.png
lrwxrwxrwx 1 ci-exec-user root 41 Aug 10 08:45 apple-touch-icon-precomposed.png -> ../app/assets/images/local_logo_small.png
lrwxrwxrwx 1 ci-exec-user root 41 Aug 10 08:45 browse_access_categories.json -> ../app/data/browse_access_categories.json
lrwxrwxrwx 1 ci-exec-user root 20 Aug 10 08:45 zip.json -> ../app/data/zip.json
```

But as cider consistently evaluates if he has to remove the that particular working directory (like every second) he writes sys logs:

```
Aug 10 09:03:47 cider-dev-hw-inx03 java[1436]: [INFO  Aug-10-Wed_09:03:47 cider-ci.ex.trials.working-dir-sweeper clojure-agent-send-off-pool-5] deleting working-dir  #object[java.io.File 0x11e75f1d /tmp/ci_working-dir/e83a5b59-3789-423e-8152-956c9aba87f4]
```

As working directories grow, this problem increases exponential ;(

**Comment by pape-io** [comment]
`rm -rf` deletes the affected working directories, so how does cider tries to delete them ?!?!

**Comment by DrTom** [comment]
Executors are as far as possible OS agnostic because they run under windows .e.g. So they don't use `rm -rf`.  There are other projects using symlinks and it works fine. It might be necessary to look at the specific case and circumstances here. Can you give me a reference to the project and branch.

**Comment by DrTom** [comment]
One more thing: while this is a bug and will be fixed there is definitely a problem with your system configuration. The executor services will rotate its own logfile and the size is capped. What is filling the logs here is the output from the console of the service managed by Systemd. Everything above and including INFO ends on the console too. A proper configured system with Systemd/jounald will never fill the disks (und let the OS crash as a side effect). Something is wrong with your system configuration and you need to fix this independently of the Cider-CI stack.

**Comment by pape-io** [comment]
I think that's solved?

**Comment by DrTom** [comment]
Yes.
