### ISSUE TITLE
Shouldn't defective trials be run on another executor again?

### ISSUE THREAD

**Issue by pape-io** [cider-ci/cider-ci#40]
<img width="1028" alt="screen shot 2016-08-18 at 10 37 02" src="https://cloud.githubusercontent.com/assets/851393/17767316/cd2a50fe-652f-11e6-9de4-d8699dc63759.png">

**Comment by pape-io** [comment]
In my opinion trials exiting with defective state shouldn't count to the max_trials.
What do you think?

**Comment by DrTom** [comment]
No. There is no sharp delimitation between the states and there needs to be a
limit for defective too. Max suggested once to set up a second independent
limit. While possibly correct I believe that this would make things more
complex without giving that many benefits.

**Comment by DrTom** [comment]
To the original question: yes. But it is (sill) not implemented yet.

**Comment by pape-io** [comment]
As you usually configure executions at the edge (like 3 trials), which as we all know creates the ~99% probability of a correct result, having 1 defective trial within those 3 decreases the probability dramatically. I'll suggest defective trial count to be the same as max_trial_count but counted separated.

**Comment by pape-io** [comment]
Superseded: https://github.com/local-ch/cider-inventory/issues/61
