### ISSUE TITLE
Ensure Webhook exists

### ISSUE THREAD

**Issue by pape-io** [cider-ci/cider-ci#44]
Couldn't the repository-service ensure, that the webhook on github exists?
I mean he has full rights on the repository usually.

Other service do the same thing, as it's quite convenient, to not have to take care about this additional step.

**Comment by pape-io** [comment]
Superseded https://github.com/local-ch/cider-inventory/issues/62

**Comment by DrTom** [comment]
Das ist auch fertig in 4.2.1.

**Comment by pape-io** [comment]
🎉
