### ISSUE TITLE
Priority: Feature Requests

### ISSUE THREAD

**Issue by pape-io** [cider-ci/cider-ci#46]
1. Defective Executor for specific task id: Increase time before next build (and we do the separate defective-trial-counter later)
2. API for repositories (read & write)
3. Manage Webhook-Triggers on Github automatically

**Comment by pape-io** [comment]
To keep also track of unprioritized feature requests:

- Count max_trials and defective_max_trials separated so that defective trials do not count as max_trials. Right now you could end up with a "defective" job because two executors have been defective.

**Comment by pape-io** [comment]
I will always update the first post in this thread to reflect current state or prioritization

**Comment by DrTom** [comment]
Number 2, API for Projects (= repositories) is now available: https://github.com/cider-ci/cider-ci/tree/4.2.0-3.0 or master. I had already startet this when you submitted the list. Next one will be 1.

**Comment by pape-io** [comment]
Superseeded by: https://github.com/local-ch/cider-inventory/projects/1
