### ISSUE TITLE
Executor not available after demo installation

### ISSUE THREAD

**Issue by pape-io** [cider-ci/cider-ci#5]
<img width="1204" alt="bildschirmfoto 2015-08-15 um 15 35 50" src="https://cloud.githubusercontent.com/assets/851393/9289068/59b07142-4363-11e5-80f3-eaec6b829032.png">

Looks like it has something to do with certificates:
```
curl https://51.254.32.165:8443
curl: (60) SSL certificate problem: Invalid certificate chain
```

I'll dig deeper...

**Comment by pape-io** [comment]
3.5.0-beta.7
![bildschirmfoto 2015-08-16 um 11 19 20](https://cloud.githubusercontent.com/assets/851393/9292699/a822ebfc-4408-11e5-92a7-437c043abeff.png)

**Comment by DrTom** [comment]
resolved
