### ISSUE TITLE
proposal: `CIDER_CI_GIT_…` env vars

### ISSUE THREAD

**Issue by eins78** [cider-ci/cider-ci#53]
Current RC exposes git branch names to the scripts via env vars. 

Current:

```sh
export CIDER_CI_CURRENT_BRANCH_HEADS=\[\"master release\"\]
```

I would have 2 use cases for this feature:
- simple checks in shell scripts (bail if not on correct branch)
- more advanced deploy scripts (like for building docs and serving static html, then aliasing the branch names)

Currently the data is not so simple to use in shell (parsing JSON), and is also missing some information that could be useful sometimes. 

With this in mind I propose the following *2* env vars:

```sh
export CIDER_CI_GIT_BRANCH_HEADS="master mfa/merge"
# use like: $ for B in $CIDER_CI_GIT_BRANCH_HEADS; do echo $B; done

export CIDER_CI_GIT_BRANCHES="{\"master":\"97a32a\",\"mfa/master\":\"97a32a\"}" 
# parse the JSON, do whatever
```

The second var is just a quick sketch, and can be improved. Maybe it should even be `CIDER_CI_GIT_META=…` with a JSON object, would be most flexible to extend in the future (I am thinking long and short ID, which ideally I want to get from git instead of truncating myself)

**Comment by DrTom** [comment]
@eins78  (FYI @spape )

The content of CIDER_CI_CURRENT_BRANCH_HEADS  is not like your example. It is a real json array, some thing like:
```
export CIDER_CI_CURRENT_BRANCH_HEADS='["v4", "test"]'
```

It is pretty simple to convert it into any format you like from json, e.g.: 
```
echo $CIDER_CI_CURRENT_BRANCH_HEADS | ruby -e "require 'JSON'; puts JSON.parse(ARGF.read).join(' ')"
```

Ruby is available on every executor installed with our deployment playbooks, practically on EVERY executor. 

Maybe some context why it ended up as json: I did not find any official git information what is allowed in branch names in about 3 minutes googling. Sure I can try some stuff and it seems that whitespaces are not. But who knows what is allowed now and what in the future. JSON just puts all discussion and pain to an end.

So I am not sure I want to change this. At least you will have to come up with something more pressing ;-)  

`CIDER_CI_GIT_META seems interesting. Unless there is no real use case we wait ;-)

**Comment by eins78** [comment]
something went wrong with the example I pasted, anyways you are correct and I just totally forgot that the executor has the traits I want ;)

In my case I'll be using node anyhow 😹 

```
node -p 'JSON.parse(process.env.CIDER_CI_CURRENT_BRANCH_HEADS).join(" ")'
```
